// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmDARiIpWmrmf0PJJXqxNiZQmnFPyeBS4',
    appId: '1:523408815634:web:c773f6ba40be9ee07c4acb',
    messagingSenderId: '523408815634',
    projectId: 'dotslash2024',
    authDomain: 'dotslash2024.firebaseapp.com',
    storageBucket: 'dotslash2024.appspot.com',
    measurementId: 'G-8VCXFWE3P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNzVfGyYoIMf-QAgPIBnLusS0ekPuWfo',
    appId: '1:523408815634:android:44aadfcf273373917c4acb',
    messagingSenderId: '523408815634',
    projectId: 'dotslash2024',
    storageBucket: 'dotslash2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx8funLncVOZczg4Q3ph16yIhA_WfK3B4',
    appId: '1:523408815634:ios:cf54062411514ca57c4acb',
    messagingSenderId: '523408815634',
    projectId: 'dotslash2024',
    storageBucket: 'dotslash2024.appspot.com',
    androidClientId: '523408815634-ftnjvn47j07q0o723sc3d7gpl6v1rn9i.apps.googleusercontent.com',
    iosClientId: '523408815634-bte24oic4absr4dqjhnob03v40peu88i.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotslash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx8funLncVOZczg4Q3ph16yIhA_WfK3B4',
    appId: '1:523408815634:ios:0bdad18f341970547c4acb',
    messagingSenderId: '523408815634',
    projectId: 'dotslash2024',
    storageBucket: 'dotslash2024.appspot.com',
    androidClientId: '523408815634-ftnjvn47j07q0o723sc3d7gpl6v1rn9i.apps.googleusercontent.com',
    iosClientId: '523408815634-51qtff3ti5qagpdaqsmcl2qfaf29j6g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dotslash.RunnerTests',
  );
}
